### ISSUE TITLE
Gamma G not working, but Night Vision H is

### ISSUE THREAD

**Issue by natbrazil** [shedaniel/ClothConfig#231]
Hi!

Running 1.20.2 Win 11 PC Java with Fabric, Iris, Sodium and your required files

Pressing 'G' shows the small text acknowledging the toggle but brightness is unchanged. However Night Vision 'H' DOES work and it's better thasn nothing for lighting things up.

Any suggestions? Can I cheat by increasing effect on Night Vision for now?

Thanks for you work and any responses.

**Comment by Sjouwer** [comment]
Hey

By a coincidence I stumbled at this, however this is not the right repository to report this issue.
This is the repository for Cloth Config and not Gamma Utils, for the latter you'd want to post it here:
https://github.com/Sjouwer/gamma-utils/issues

In any case, to me it sounds like you're using shaders.
Shaders use their own lighting systems and pretty much none will take into account Gamma.
That's why the Gamma change won't do anything for you.
As you noticed though, many do work with Night Vision.
However, the implementation of that lays with the creator of the shaders.
You could try out different shaders to see if Night Vision works better with those.

If you got any more issues with the Gamma Utils mod, please post them on the Gamma Utils repository instead of this one.
I also recommend closing this one, as this issue is not related to Cloth Config.

**Comment by natbrazil** [comment]
Thx so much for your response
